"""Purchase-order generation for ConstructIQ.

A PO can only be generated from an ACCEPTED negotiation (human-approved
price). The PDF is laid out with ReportLab Platypus and written to
``config.PO_DIR``; the row is persisted with an initial ``draft`` tracking
event so the timeline starts at creation.
"""
from __future__ import annotations

import logging
from datetime import date, timedelta
from pathlib import Path

from sqlalchemy.orm import Session

from backend import config
from backend.db.models import (
    Negotiation,
    PurchaseOrder,
    TrackingEvent,
    Vendor,
    VendorQuote,
)

logger = logging.getLogger(__name__)

FOOTER_TEXT = (
    "Generated by ConstructIQ — demo prototype, not a legally binding document"
)
# Built-in PDF fonts have no ₹ glyph, so amounts are rendered as "INR ..." in the PDF.
_PDF_CURRENCY = "INR"


def _format_amount(amount: float) -> str:
    return f"{_PDF_CURRENCY} {amount:,.2f}"


def _payment_terms_for(vendor_id: int, material: str, db_session: Session) -> str:
    """Payment terms from the vendor's matching quote, else 'Net 30'."""
    quotes = db_session.query(VendorQuote).filter(VendorQuote.vendor_id == vendor_id).all()
    material_lower = (material or "").lower()
    for quote in quotes:
        quote_material = (quote.material or "").lower()
        if material_lower in quote_material or quote_material in material_lower:
            if quote.payment_terms:
                return quote.payment_terms
    return "Net 30"


def _render_pdf(
    pdf_path: Path,
    po_number: str,
    negotiation: Negotiation,
    vendor: Vendor,
    quantity: float,
    unit_price: float,
    total_amount: float,
    delivery_date: date,
    payment_terms: str,
) -> None:
    """Lay out the PO with ReportLab Platypus and write it to ``pdf_path``."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "POTitle", parent=styles["Title"], fontSize=22, spaceAfter=2
    )
    subtitle_style = ParagraphStyle(
        "POSubtitle", parent=styles["Heading2"], textColor=colors.HexColor("#334155")
    )
    footer_style = ParagraphStyle(
        "POFooter",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#64748B"),
    )

    details_rows: list[list[str]] = [
        ["Project", negotiation.project_id],
        ["Vendor", vendor.name],
        ["Vendor location", f"{vendor.location or '—'} ({vendor.region or 'India'})"],
        ["Vendor contact", vendor.contact_email or vendor.contact_phone or "—"],
        ["Material", negotiation.material or "—"],
        ["Grade", negotiation.grade or "—"],
        ["Quantity", f"{quantity:g} {negotiation.unit}"],
        ["Unit price", f"{_format_amount(unit_price)} per {negotiation.unit}"],
        ["Expected delivery", delivery_date.isoformat()],
        ["Payment terms", payment_terms],
        ["Order date", date.today().isoformat()],
    ]
    details_table = Table(details_rows, colWidths=[45 * mm, 115 * mm])
    details_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F1F5F9")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )

    totals_rows = [
        ["Subtotal", _format_amount(total_amount)],
        ["TOTAL", _format_amount(total_amount)],
    ]
    totals_table = Table(totals_rows, colWidths=[45 * mm, 115 * mm])
    totals_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica"),
                ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 11),
                ("LINEABOVE", (0, 1), (-1, 1), 1, colors.HexColor("#0F172A")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#F1F5F9")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )

    story = [
        Paragraph("PURCHASE ORDER", title_style),
        Paragraph(po_number, subtitle_style),
        Spacer(1, 6 * mm),
        details_table,
        Spacer(1, 6 * mm),
        totals_table,
        Spacer(1, 12 * mm),
        Paragraph(FOOTER_TEXT, footer_style),
    ]

    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        title=po_number,
        author="ConstructIQ",
    )
    doc.build(story)


def generate_po(negotiation_id: int, db_session: Session) -> PurchaseOrder:
    """Generate a PurchaseOrder (row + PDF) from an accepted negotiation.

    Raises ``ValueError`` when the negotiation is missing, not accepted, has
    no agreed final price, or has no stated quantity (a zero-quantity PO would
    be a signed-off document with TOTAL 0.00).
    """
    negotiation = db_session.get(Negotiation, negotiation_id)
    if negotiation is None:
        raise ValueError(f"Negotiation {negotiation_id} not found")
    if negotiation.status != "accepted":
        raise ValueError(
            "Purchase orders can only be generated from an accepted negotiation "
            f"(current status: {negotiation.status})"
        )
    if negotiation.final_price is None:
        raise ValueError(
            f"Negotiation {negotiation_id} is accepted but has no final price"
        )
    if not negotiation.quantity or negotiation.quantity <= 0:
        raise ValueError(
            f"Negotiation {negotiation_id} has no stated quantity — the source "
            "requirement did not state one; set a quantity before generating "
            "a purchase order"
        )
    vendor = db_session.get(Vendor, negotiation.vendor_id)
    if vendor is None:
        raise ValueError(f"Vendor {negotiation.vendor_id} not found")

    # Sequential PO number per project: count existing + 1, zero-padded to 4.
    existing_count = (
        db_session.query(PurchaseOrder)
        .filter(PurchaseOrder.project_id == negotiation.project_id)
        .count()
    )
    po_number = f"PO-{negotiation.project_id}-{existing_count + 1:04d}"

    unit_price = negotiation.final_price
    quantity = negotiation.quantity
    total_amount = round(quantity * unit_price, 2)
    delivery_date = date.today() + timedelta(days=vendor.avg_delivery_days or 0)
    payment_terms = _payment_terms_for(vendor.id, negotiation.material, db_session)

    po_dir = Path(config.PO_DIR)
    po_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = po_dir / f"{po_number}.pdf"
    _render_pdf(
        pdf_path,
        po_number,
        negotiation,
        vendor,
        quantity,
        unit_price,
        total_amount,
        delivery_date,
        payment_terms,
    )

    po = PurchaseOrder(
        project_id=negotiation.project_id,
        negotiation_id=negotiation.id,
        po_number=po_number,
        vendor_id=vendor.id,
        material=negotiation.material,
        grade=negotiation.grade,
        quantity=quantity,
        unit=negotiation.unit,
        unit_price=unit_price,
        total_amount=total_amount,
        delivery_date=delivery_date,
        payment_terms=payment_terms,
        status="draft",
        pdf_path=str(pdf_path),
    )
    db_session.add(po)
    db_session.flush()
    db_session.add(
        TrackingEvent(
            purchase_order_id=po.id,
            status="draft",
            note=f"Purchase order {po_number} generated from negotiation {negotiation.id}",
        )
    )
    db_session.commit()
    logger.info(
        "Generated %s for vendor %s: %s x %.2f = %.2f INR (%s)",
        po_number,
        vendor.name,
        quantity,
        unit_price,
        total_amount,
        pdf_path,
    )
    return po
